# docker-compose.yml

services:
  front:
    build:
      context: ./front
    image: kingheedo/reactchat-front:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=dhkdgmleh@gmail.com
      - CERTBOT_DOMAIN1=reactchat.online
      - CERTBOT_DOMAIN2=www.reactchat.online
    volumes:
      - ./front:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt