# docker-compose.yml

services:
  front:
    build:
      context: ./front
    image: kingheedo/reactchat-front:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt