# docker-compose.yml

services:
  front:
    build:
      context: ./front
    ports:
      - "3090:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./back
  #   ports:
  #     - "3095:3095"

volumes:
  certbot-etc:
  certbot-var: