# docker-compose.yml

services:
  front:
    build:
      context: ./front
    ports:
      - "3090:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment:
      - CERTBOT_EMAIL=dhkdgmleh@gmail.com
      - CERTBOT_DOMAIN1=reactchat.online
      - CERTBOT_DOMAIN2=www.reactchat.online
      - CERTBOT_DOMAIN3=api.reactchat.online
    command: >
      sh -c "nginx -g 'daemon off;' & while :; do certbot renew --nginx --non-interactive --agree-tos --email $CERTBOT_EMAIL --domains $CERTBOT_DOMAIN1,$CERTBOT_DOMAIN2,$CERTBOT_DOMAIN3; sleep 12h; done"
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./back
  #   ports:
  #     - "3095:3095"

volumes:
  certbot-etc:
  certbot-var: