# docker-compose.yml

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: kingheedo/reactchat:latest # 이미지 이름을 지정합니다
    # container_name: reactchat # 컨테이너 이름을 지정합니다
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    certbot:
      image: certbot/certbot
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/lib/letsencrypt:/var/lib/letsencrypt
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
