name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy Nginx files to frontend directory
      run: |
        cp -r nginx front/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push frontend Docker image
      run: |
        docker build -t kingheedo/reactchat-front:latest ./front
        docker push kingheedo/reactchat-front:latest

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-avz --delete"
      with:
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        target: ${{ secrets.REMOTE_TARGET }}

    - name: Restart Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.REMOTE_TARGET }}
          docker-compose down
          docker-compose up -d
        EOF

