name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy Nginx files to frontend directory
      run: |
        cp -r nginx front/

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd front
        npm install

    - name: Build the React app
      run: |
        cd front
        npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd front
        docker build -t kingheedo/reactchat-front:latest .
        docker push kingheedo/reactchat-front:latest

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-avz --delete"
      with:
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        target: ${{ secrets.REMOTE_TARGET }}

    - name: Restart Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.REMOTE_TARGET }}
          docker-compose down
          docker-compose up -d
        EOF
