name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --pasword-stdin

      - name: Build and push Docker image
        run: |
          docker build -t reactchathttps:latest .
          docker tag reactchathttps:latest kingheedo/reactchathttps:latest
          docker push kingheedo/reactchathttps:latest

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          scritp: |
            docker pull kingheedo/reactchathttps:latest
            docker stop reactchathttps || true
            docker rm reactchathttps || true
            docker run -d -p 80:80 --name reactchathttps kingheedo/reactchathttps:latest
