name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'front')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temporary project directory on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/react-chat-temp
            sudo chown ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /home/ubuntu/react-chat-temp
      
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP to temporary directory
        run: |
          scp -r -i ~/.ssh/id_rsa * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/react-chat-temp

      - name: Move files to project directory and set permissions
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/react-chat
            sudo cp -r /home/ubuntu/react-chat-temp/* /home/ubuntu/react-chat/
            sudo rm -rf /home/ubuntu/react-chat-temp

      # - name: Install Docker on EC2
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo apt-get update
      #       sudo apt-get install -y \
      #         ca-certificates \
      #         curl \
      #         gnupg \
      #         lsb-release
      #       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      #       echo \
      #         "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      #         $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      #       sudo apt-get update
      #       sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      #       sudo systemctl start docker
      #       sudo systemctl enable docker

      # - name: Install Docker Compose on EC2
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #       sudo chmod +x /usr/local/bin/docker-compose
      #       sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      #       sudo docker-compose --version
      
      # - name: Install Nginx and Certbot on EC2
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo apt-get update
      #       sudo apt-get install -y nginx certbot python3-certbot-nginx

      - name: Ensure Docker is running
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo systemctl status docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push front Docker image
        run: |
          docker buildx build --no-cache --push --tag ${{ secrets.DOCKER_USERNAME }}/reactchat-ec2:latest ./front

      - name: Pull Docker images
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/react-chat
            sudo docker-compose pull

      # - name: Increase Swap Memory
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo fallocate -l 2G /swapfile
      #       sudo chmod 600 /swapfile
      #       sudo mkswap /swapfile
      #       sudo swapon /swapfile
      #       echo '/swapfile swap swap defaults 0 0' | sudo tee -a /etc/fstab

        # - name: Obtain initial SSL certificates
        #  uses: appleboy/ssh-action@v0.1.7
        #  with:
        #    host: ${{ secrets.EC2_HOST }}
        #    username: ${{ secrets.EC2_USER }}
        #    key: ${{ secrets.EC2_SSH_KEY }}
        #    script: |
        #      cd /home/ubuntu/react-chat
        #      sudo docker-compose down
        #      sudo certbot --nginx -d reactchat.online -d www.reactchat.online -d api.reactchat.online --non-interactive --agree-tos --email dhkdgmleh@gmail.com

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/react-chat/front
            #sudo systemctl stop nginx
            sudo docker-compose down front
            sudo docker-compose up -d front
            sudo docker-compose up -d nginx

      #- name: Set up cron job for certificate renewal
      #  uses: appleboy/ssh-action@v0.1.7
      #  with:
      #    host: ${{ secrets.EC2_HOST }}
      #    username: ${{ secrets.EC2_USER }}
      #    key: ${{ secrets.EC2_SSH_KEY }}
      #    script: |
      #      echo "0 0 * * * /usr/bin/certbot renew --quiet && sudo systemctl reload nginx" | sudo tee -a /etc/crontab
  
  deploy-back:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'back')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temporary project directory on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/react-chat-temp
            sudo chown ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /home/ubuntu/react-chat-temp
      
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP to temporary directory
        run: |
          scp -r -i ~/.ssh/id_rsa * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/react-chat-temp

      - name: Move files to project directory and set permissions
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/react-chat
            sudo cp -r /home/ubuntu/react-chat-temp/* /home/ubuntu/react-chat/
            sudo rm -rf /home/ubuntu/react-chat-temp

      - name: Ensure Docker is running
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo systemctl status docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push front Docker image
        run: |
          docker buildx build --no-cache --push --tag ${{ secrets.DOCKER_USERNAME }}/reactchat-ec2:latest ./back

      - name: Pull Docker images
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/react-chat
            sudo docker-compose pull

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/react-chat
            #sudo systemctl stop nginx
            sudo docker-compose down mysql
            sudo docker-compose down back
            sudo docker-compose up -d mysql
            sudo docker-compose up -d back
            sudo docker-compose up -d nginx